<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Current Address_currentAddress</name>
   <tag></tag>
   <elementGuidId>e401be10-e1c7-4c90-b786-633781df87a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#currentAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='currentAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d8675dc4-1396-4faf-b118-2f80a13d55dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Current Address</value>
      <webElementGuid>af4f94cc-b275-4144-b94b-b5fd9c7dd230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>0930ca4d-c513-4e01-877e-b5f261ac2254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>aeedcf4c-af69-40b2-9b02-1f5d6dc4ed8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>currentAddress</value>
      <webElementGuid>f4fffddd-9ae1-408c-9008-14730c5ff80a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>736e62c0-7f00-4cd3-905e-bcc9d59ba708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;currentAddress&quot;)</value>
      <webElementGuid>16f6d491-cb2a-4730-ae60-adf36ae49a72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='currentAddress']</value>
      <webElementGuid>ef77fb88-fd0b-4649-9d7c-64474e6555a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='currentAddress-wrapper']/div[2]/textarea</value>
      <webElementGuid>59225796-54e4-4f83-aded-5b8b154d2f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>56b3e01f-30c8-40f4-9018-e884d6d6fd13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Current Address' and @id = 'currentAddress']</value>
      <webElementGuid>4acacf18-681a-46ad-8021-9c4023431354</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
