<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_360</name>
   <tag></tag>
   <elementGuidId>7e77385f-e40d-41fb-baf5-f855be315cba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#totalp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h3[@id='totalp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>0b2462de-c9eb-4e09-9b8d-47e0c65606b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-title</value>
      <webElementGuid>7bbbc2fc-180e-437c-a869-a86397e1c8ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>totalp</value>
      <webElementGuid>91e1a7b5-487a-4be7-91f6-b2b36bd20c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>360</value>
      <webElementGuid>b30207d2-12bc-46ab-8857-5a6f388f2ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;totalp&quot;)</value>
      <webElementGuid>babb0e7a-d2bc-481a-8c6d-d249bf0c7493</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h3[@id='totalp']</value>
      <webElementGuid>a8d2309a-8d15-484d-b56c-ac7568633b5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div/div[2]/div/div/h3</value>
      <webElementGuid>be028e88-e43b-4214-b6d1-feb43e46ff96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::h3[1]</value>
      <webElementGuid>02f78b79-c2bd-4268-9da5-2ddf32301d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Samsung galaxy s6'])[1]/following::h3[1]</value>
      <webElementGuid>007b1e26-4086-4964-b045-9332344ced70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Place Order'])[1]/preceding::h3[1]</value>
      <webElementGuid>2bc0577d-f870-4862-a7b4-308602c0ad7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[1]/preceding::h3[1]</value>
      <webElementGuid>63ea7cc6-ba4e-464e-ba51-7fa7ef0b4148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>3943f9bf-d936-48b1-be87-4407b65ab531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[@id = 'totalp' and (text() = '360' or . = '360')]</value>
      <webElementGuid>b1b3530d-ed74-413d-a628-dbc78a1bc7bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
